### PR TITLE
Mute file_exists errors (removed system calls)

### LINKED ISSUE #626: open_basedir warnings
Hi,

With 1.10, I have such warnings in logs :
```
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/sbin/sendmail) is not within the allowed path(s) in fonctions_conges.php on line 512
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/var/qmail/bin/sendmail) is not within the allowed path(s) in fonctions_conges.php on line 514
```

Could we switch them off ?
For example using `@file_exists()` writing ?

Perhaps there are other occurrences of functions trying to access system files,
I did not go through all the code.

Thank you 👍 

Ben

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This tiny PR solves and then closes #626.

As it has no impact at all, could we think about having it in next release please ?

Thank you very much :+1:

### CODE REVIEW

**Comment by prytoegrian** [comment]
Same as @codacy-bot, silencing errors is a bad practice. I would rather delegate the sending mail process to PHPMailer ie. use SMTP as defined in `cfg/config_SMTP.php` if it's set, and use php's mail() function otherwise. All other stuff isn't necessary. Actually, I'd throw theses checks.

Thanks to **you**.

**Comment by benrubson** [comment]
Do you then plan to get rid of the other checks (especially the `file_exists` calls) through another PR ?
Many thx @prytoegrian 👍

**Comment by prytoegrian** [comment]
We can directly do it in this PR, you just have to remove `file_exists` calls :-)

**Comment by benrubson** [comment]
Yes you're right :)
Just done then !
Feel free to squash-merge if you want.
Thank you 👍

**Comment by prytoegrian** [comment]
For improving the future release's content, I took the liberty of changing your title.

**Comment by prytoegrian** [comment]
:heart:

**Comment by benrubson** [comment]
Many thanks @prytoegrian :+1:

**Pull request merged**
